### ISSUE TITLE
出现 Exceeded 30 redirects，无法通过ip查域名

### ISSUE THREAD

**Issue by lzyhenniu** [snowfal1/CloudflareCDNFission#2]
请求修复重定向次数过多的问题

**Comment by snowfal1** [comment]
经测试一切正常，脚本中设置了三个ip反查的网站，大量请求下有些站会被风控，但脚本会自动切换到另一个站，如果这种情况下还是出现了风控，建设切换本地网络环境或者调小 `max_workers_request` 的值。

**Comment by lzyhenniu** [comment]
`max_workers_request`的值调整为2，但仍然出现 Exceeded 30 redirects。难道是服务器的ip被拉黑了？
　
　
![image](https://github.com/snowfal1/CloudflareCDNFission/assets/92658867/de1a8a9b-3fc1-4394-ba1f-e1f8ab95255c)
通过ip查域名仍然出现 Exceeded 30 redirects。

　
　
　

![image](https://github.com/snowfal1/CloudflareCDNFission/assets/92658867/0b968acb-c89f-4adb-804f-f4e4907122cd)
通过域名查ip没问题

**Comment by snowfal1** [comment]
切换本地网络环境试试

**Comment by lzyhenniu** [comment]
> 切换本地网络环境试试

好的
